kind: Deployment
apiVersion: apps/v1
metadata:
  name: springboot-movie-people-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: springboot-movie-people-api
  template:
    metadata:
      labels:
        app: springboot-movie-people-api
    spec:
      containers:
      - name: springboot-movie-people-api
        image: dandonghukim/springboot-movie-people-api:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef: 
              name: moviedb-config
              key: db-host
        - name: DB_PORT
          valueFrom:
            configMapKeyRef: 
              name: moviedb-config
              key: db-port
        - name: DB_SERVICE_NAME
          valueFrom:
            configMapKeyRef: 
              name: moviedb-config
              key: db-service-name
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: moviedb-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: moviedb-secret
              key: password
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-movie-people-api-svc
spec:
  selector:
    app: springboot-movie-people-api
  ports:
    - port: 31000
      targetPort: 8080
  type: ClusterIP
