kind: Deployment
apiVersion: apps/v1
metadata:
  name: helidon-movie-api-mp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: helidon-movie-api-mp
  template:
    metadata:
      labels:
        app: helidon-movie-api-mp
    spec:
      containers:
        - name: helidon-movie-api-mp
          image: icn.ocir.io/axlpeslmb1ng/movie/helidon-movie-api-mp:dbe1d762a5545875243a2ae3070a79b7578dd891
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
      imagePullSecrets:
        - name: ocirsecret
