kind: Deployment
apiVersion: apps/v1
metadata:
  name: jet-movie-msa-ui
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jet-movie-msa-ui
  template:
    metadata:
      labels:
        app: jet-movie-msa-ui
    spec:
      containers:
        - name: jet-movie-msa-ui
          image: dandonghukim/jet-movie-msa-ui:ef626bc98c74aff099cce48d24fff8e6b3449532
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
      imagePullSecrets:
        - name: ocirsecret
