kind: Deployment
apiVersion: apps/v1
metadata:
  name: jet-movie-msa-ui
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jet-movie-msa-ui
  template:
    metadata:
      labels:
        app: jet-movie-msa-ui
    spec:
      containers:
        - name: jet-movie-msa-ui
          image: dandonghukim/jet-movie-msa-ui:1538ba9923f76171245a12eba1a4d45ae5e983b9
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
