apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: jet-movie-msa-ui
spec:
  replicas: 10
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: jet-movie-msa-ui
  template:
    metadata:
      labels:
        app: jet-movie-msa-ui
    spec:
      containers:
        - name: jet-movie-msa-ui
          image: icn.ocir.io/axlpeslmb1ng/movie/jet-movie-msa-ui:ba76d1c94b072f99c997924dee86ac9eec7c03c9
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
      imagePullSecrets:
        - name: ocirsecret
  strategy:
    canary:
      maxSurge: "20%"
      maxUnavailable: 0
      steps:
        - setWeight: 20
        - pause: {}
