kind: Deployment
apiVersion: apps/v1
metadata:
  name: jet-movie-msa-ui
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jet-movie-msa-ui
  template:
    metadata:
      labels:
        app: jet-movie-msa-ui
    spec:
      containers:
        - name: jet-movie-msa-ui
          image: dandonghukim/jet-movie-msa-ui:3bee01602932128cb56018f0eaf53e29169392d2
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
