kind: Deployment
apiVersion: apps/v1
metadata:
  name: jet-movie-msa-ui
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jet-movie-msa-ui
  template:
    metadata:
      labels:
        app: jet-movie-msa-ui
    spec:
      containers:
        - name: jet-movie-msa-ui
          image: dandonghukim/jet-movie-msa-ui:603e79d06b5849d6ad809005de619839a992afb6
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
