apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: jet-movie-msa-ui
spec:
  replicas: 8
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: jet-movie-msa-ui
  template:
    metadata:
      labels:
        app: jet-movie-msa-ui
    spec:
      containers:
        - name: jet-movie-msa-ui
          image: dandonghukim/jet-movie-msa-ui:106dec64c95aed1b1c5ea7608686fdd75c5316e2
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
  strategy:
    canary:
      maxSurge: "25%"
      maxUnavailable: 0
      steps:
        - setWeight: 25
        - pause: {}
